name: Half-year calendar
on:
  on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  create-calendar:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.isocalendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        plugin_isocalendar: yes
