name: Icons
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  create-calendar:
    runs-on: ubuntu-latest
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.topics.icons.svg
        token: NOT_NEEDED
        base: "python, django, docker, sql, firebase, pytorch,javascript"
        plugin_topics: yes
        plugin_topics_limit: 0
        plugin_topics_mode: icons
